#!/usr/bin/env node
// Puts `catalogus` on PATH by writing small shims into the directory the
// package manager already exposes, pointing them at this checkout's built
// CLI.
//
// Why shims rather than a global install. `packages/cli` depends on
// `@catalogus/core` and `@catalogus/schema` through the `workspace:*`
// protocol, so `pnpm add --global ./packages/cli` tries to resolve those two
// from the registry and fails -- they are not published. pnpm 11 also
// dropped `pnpm link --global`. A shim sidesteps both: it runs the built
// entrypoint in place, so Node resolves dependencies from the checkout's own
// node_modules exactly as `node packages/cli/dist/cli.js` does, and every
// `pnpm build` updates what the shim runs without relinking.
//
// Run with --remove to delete the shims again. Nothing here edits PATH; the
// target directory is one that is already on it.
import { chmod, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { execFileSync } from "node:child_process";
import { delimiter, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cliEntry = join(repoRoot, "packages", "cli", "dist", "cli.js");
const isWindows = process.platform === "win32";
const remove = process.argv.includes("--remove");

/**
 * Where to write. npm's global bin directory, because it is the one place
 * that is on PATH on a stock Node install; pnpm's own global bin needs
 * `pnpm setup` to have been run first, which is a change to the user's
 * environment this script deliberately does not make.
 */
function globalBinDir() {
  try {
    // npm.cmd by name rather than `shell: true`: passing args through a
    // shell is deprecated in Node 22+ and warns on every run.
    const npm = isWindows ? "npm.cmd" : "npm";
    const prefix = execFileSync(npm, ["prefix", "-g"], { encoding: "utf8" }).trim();
    if (prefix) {
      // On Windows npm puts binaries directly in the prefix; elsewhere in prefix/bin.
      return isWindows ? prefix : join(prefix, "bin");
    }
  } catch {
    // npm not on PATH -- fall through to the platform default.
  }
  if (isWindows) {
    const appData = process.env.APPDATA;
    if (!appData) {
      throw new Error("could not determine npm's global bin directory, and %APPDATA% is unset");
    }
    return join(appData, "npm");
  }
  return "/usr/local/bin";
}

function shimFiles(targetDir) {
  const files = [{ path: join(targetDir, "catalogus"), mode: 0o755, content: posixShim() }];
  if (isWindows) {
    files.push({ path: join(targetDir, "catalogus.cmd"), content: cmdShim() });
    files.push({ path: join(targetDir, "catalogus.ps1"), content: powershellShim() });
  }
  return files;
}

// Git Bash and every POSIX shell. Node on Windows accepts a forward-slashed
// absolute path, so one form covers both.
function posixShim() {
  return `#!/bin/sh
# Generated by "pnpm run link:cli" in ${repoRoot.replace(/\\/g, "/")}
exec node "${cliEntry.replace(/\\/g, "/")}" "$@"
`;
}

function cmdShim() {
  return `@ECHO off\r
REM Generated by "pnpm run link:cli" in ${repoRoot}\r
SETLOCAL\r
node "${cliEntry}" %*\r
EXIT /b %ERRORLEVEL%\r
`;
}

function powershellShim() {
  return `#!/usr/bin/env pwsh
# Generated by "pnpm run link:cli" in ${repoRoot}
& node "${cliEntry}" @args
exit $LASTEXITCODE
`;
}

function isOnPath(dir) {
  const entries = (process.env.PATH ?? "").split(delimiter).filter(Boolean);
  const wanted = resolve(dir).toLowerCase();
  return entries.some((entry) => {
    try {
      return resolve(entry).toLowerCase() === wanted;
    } catch {
      return false;
    }
  });
}

async function main() {
  const targetDir = globalBinDir();
  const files = shimFiles(targetDir);

  if (remove) {
    for (const file of files) {
      await rm(file.path, { force: true });
    }
    console.log(`Removed the catalogus shims from ${targetDir}`);
    return;
  }

  // A shim pointing at a file that does not exist reports itself as a Node
  // "cannot find module" error, which reads like a broken install rather
  // than a missing build.
  try {
    await readFile(cliEntry);
  } catch {
    console.error(`${cliEntry} does not exist -- run "pnpm build" first, then this again.`);
    process.exitCode = 1;
    return;
  }

  await mkdir(targetDir, { recursive: true });
  for (const file of files) {
    await writeFile(file.path, file.content, "utf8");
    if (file.mode !== undefined && !isWindows) {
      await chmod(file.path, file.mode);
    }
  }

  console.log(`Linked "catalogus" -> ${cliEntry}`);
  console.log(`  shims written to ${targetDir}`);
  if (isOnPath(targetDir)) {
    // No PATH change happened -- only files appeared in a directory already
    // on it -- so an already-open shell finds them too. No restart needed.
    console.log("  that directory is already on PATH; run: catalogus --version");
  } else {
    console.log(`  WARNING: ${targetDir} is not on PATH. Add it, or run the CLI by full path.`);
  }
  console.log('  the shims point at this checkout, so "pnpm build" updates them in place.');
  console.log('  undo with "pnpm run unlink:cli".');
}

await main();
