// Builds the text of supabase/seed.sql from the Catalogus service catalog.
// Factored out of generate-seed.mjs so seed-sync.test.ts can import the
// exact same SQL-building logic the generator uses, rather than
// reimplementing it as a second copy that could drift -- the same split
// packages/schema/scripts/generate-schema-json.mjs keeps thin against
// schema-sync.test.ts.
//
// Only slug, name and icon_ref are ever written by the statement this
// builds, and only ever *overwritten* on conflict: pricing_model and
// vendor_url are not in this repo (CLAUDE.md's "ask, never guess" rule --
// see docs/plan/decisions.md, decision 15), and status, sunset_date and
// successor_service_id are the owner's own hand-authored data once a row
// exists -- none of the five appears in this statement's column list, which
// is what keeps a reseed from clobbering any of them.

/** Doubles single quotes for a SQL string literal and wraps the result in quotes. */
function sqlString(value) {
  return `'${value.replace(/'/g, "''")}'`;
}

/** `null` (unquoted) for a catalog entry with no icon; a quoted string literal otherwise. */
function sqlIconRef(icon) {
  return icon === undefined ? "null" : sqlString(icon);
}

const HEADER = `-- Generated by packages/db/scripts/generate-seed.mjs from CATALOGUS_CATALOG
-- (@catalogus/core, packages/core/src/catalog.ts) -- do not hand-edit. Regenerate
-- with \`pnpm --filter @catalogus/db build\` (or the root \`pnpm build\`, which
-- runs it for every package), after any change to the catalog.
--
-- pricing_model and vendor_url are left null on purpose: neither fact is in
-- this repo, and CLAUDE.md's "ask, never guess" rule means this generator
-- does not invent one (see docs/plan/decisions.md, decision 15). The owner
-- fills them in by hand, in the dashboard, or with a later command, once one
-- exists to do it from the CLI.
--
-- The insert below is idempotent (\`on conflict (slug) do update\`) and its
-- column list is exactly (slug, name, icon_ref) on both sides of the
-- conflict -- pricing_model, vendor_url, status, sunset_date and
-- successor_service_id never appear in it, so a value the owner has set by
-- hand on any of those columns survives every reseed unchanged.
`;

/**
 * Builds the full contents of supabase/seed.sql from a catalog shaped like
 * CATALOGUS_CATALOG (slug -> { slug, name, icon? }). Deterministic: rows
 * sorted by slug, one row per line, LF line endings, trailing newline.
 */
export function buildSeedSql(catalog) {
  const rows = Object.values(catalog).sort((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0));

  const values = rows
    .map((row) => `  (${sqlString(row.slug)}, ${sqlString(row.name)}, ${sqlIconRef(row.icon)})`)
    .join(",\n");

  const statement = `insert into services (slug, name, icon_ref) values
${values}
on conflict (slug) do update set
  name = excluded.name,
  icon_ref = excluded.icon_ref;
`;

  return `${HEADER}\n${statement}`;
}
